config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get '/.well-known/acme-challenge/xrXJjczoBkcC6IdjRfHaauucSXBFj9zji_JkTe5PRN4' => 'ssl_certificates#letsencrypt'
  get 'admin/home'
  get 'feed' => 'posts#feed', defaults: { format: :atom }

  resources :posts

  root 'landing#about'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true,
                    uniqueness: true,
                    length: { minimum: 5 }

  def raw_text
  end

  def raw_title
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def home
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :edit, :destroy]

  def index
    @posts = Post.order(created_at: :desc).all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def feed
    @posts = Post.order(created_at: :desc).all
    respond_to do |format|
      format.atom { render :layout => false  }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end

end

app/controllers/ssl_certificates_controller.rb
class SslCertificatesController < ApplicationController

  def letsencrypt
    render plain: 'xrXJjczoBkcC6IdjRfHaauucSXBFj9zji_JkTe5PRN4.gRfRobaJJWWVuW3_tyomWzvJvLvutWEqVHfqexKeFlo'
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/home.html.erb
<h1>Admin Dashboard</h1>
<ul>
   <li><%= link_to 'Posts', posts_path %></li>
   <li><%= link_to 'New Post', new_post_path %></li>
</ul>

app/views/landing/about.html.erb
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-6">
    Hi there, my name is Adam. I'm a software developer with expertise in Ruby
    on Rails. I also have experience with front end Javascript frameworks 
    such as Ember and React.
    <br>
    <br>
    I'm passionate about open source software, and in my free time I like
    to contribute to <%= link_to('Bundler', 'https://github.com/bundler/bundler/commits?author=ajwann') %>
  and <%= link_to('Exercism.io', 'https://github.com/exercism/ruby/commits?author=ajwann') %>.
  <br>
  <br>
  I currently live and work in Columbus OH, where I am also active in the
  local Ruby on Rails scene. You can often find me at the 
  <%= link_to('Mutually Human Hack Night', 'https://www.meetup.com/Mutually-Human-Hack-Night') %>
  and the <%= link_to('Columbus Ruby Brigade', 'http://columbusrb.com/' ) %>.
<br>
<br>
Feel free to check out my <%= link_to('GitHub', 'https://www.github.com/ajwann') %> or
my <%= link_to('blog', posts_path) %>.
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="row">
  <div class="col-md-2">
  </div>

  <div class="col-md-4">
    <div class="light-padding-top">
      <%= image_tag "me.png", height: "230", width: "230", class: "rounded-circle" %>
    </div>
  </div>
  <div class="col-md-4">
    <div class="light-padding-top">

      <div class='pull-right'>
        <div class='row'>
          <div class="col-md-10">
            <div class='pull-right'>
              <span>
                <%= link_to "<i class='fa fa-github fa-2x'    name='GitHub' aria-hidden='true'></i>".html_safe, 'https://github.com/ajwann' %>
                <%= link_to "<i class='fa fa-file-text fa-2x' name='Resume' aria-hidden='true'></i>".html_safe, '' %>
                <%= link_to "<i class='fa fa-envelope fa-2x'  name='Email'  aria-hidden='true'></i>".html_safe, 'mailto:ajwann@ajwann.com' %>
              </span>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A Gem of a Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= auto_discovery_link_tag(:atom, "#{root_path}/feed.rss", {title: "A Gem of a Blog"} ) %>
    <script>hljs.initHighlightingOnLoad();</script>
  </head>

  <body>
      <div class="container">
        <%= render "layouts/header" %>
        <%= yield %>
      </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, size: 50 %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, rows: 10, cols: 70 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/_post.html.erb
<h3><%= link_to "#{markdown.render(post.title)}".html_safe, post, class:'title-link' %></h3>
<p><small><%= post.created_at.strftime('%Y-%m-%d') %></small></p>
<%= markdown.render(post.text).html_safe %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
 
<%= render 'form' %> 

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="row">
  <div class="col-md-12">
    <%= render 'post', post: post %>
    <% if admin_signed_in? %>
      &nbsp
      <br>
      <%= link_to 'Show', post_path(post) %>&nbsp
      <%= link_to 'Edit', edit_post_path(post) %>&nbsp
      <%= link_to 'Destroy', post_path(post),
                             method: :delete,
                             data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>
  <br>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-12">
      <%= render 'post', post: @post %>
    <% if admin_signed_in? %>
      &nbsp
      <br>
      <%= link_to 'Edit', edit_post_path(@post) %>&nbsp
      <%= link_to 'Destroy', post_path(@post),
                             method: :delete,
                             data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>